In [2]:
import pandas as pd
file = open('source.txt', mode='r')
text = file.read()
text

'Not so simple any more'

In [3]:
file.read() # File gonna read only once

''

In [4]:
file.closed #File connection is not close can be altered not a good practice to keep it open after using it

False

In [5]:
file.close() # To close connection

In [6]:
file.closed

True

**Using with open**

In [7]:
with open('source.txt', mode='w') as file_output:
    file_output.write("Not so simple any more")

In [8]:
with open ('source.txt', mode='rt') as file_output:
    text=file_output.read()

In [9]:
print(text)

Not so simple any more


**Importing CSV with pandas**

In [10]:
Data=pd.read_csv("Lending-company.csv")

In [11]:
type(pd.read_csv("Lending-company.csv"))

pandas.core.frame.DataFrame

In [12]:
pd.read_csv("Lending-company.csv", header=0)

LoanID     StringID    Product CustomerGender     Location    Region  \
0          1     LoanID_1  Product B         Female   Location 3  Region 2   
1          2     LoanID_2  Product D         Female   Location 6  Region 6   
2          3     LoanID_3  Product B           Male   Location 8  Region 3   
3          4     LoanID_4  Product A           Male  Location 26  Region 2   
4          5     LoanID_5  Product B         Female  Location 34  Region 3   
...      ...          ...        ...            ...          ...       ...   
1038    1039  LoanID_1039  Product B           Male  Location 73  Region 6   
1039    1040  LoanID_1040  Product A           Male  Location 82  Region 1   
1040    1041  LoanID_1041  Product A   NotSpecified  Location 11  Region 4   
1041    1042  LoanID_1042  Product B         Female  Location 26  Region 6   
1042    1043  LoanID_1043  Product A   NotSpecified  Location 94  Region 6   

      TotalPrice   StartDate  Deposit  DailyRate  TotalDaysYr  AmtPaid36  \
0        17600.0  04/07/2018     2200         45          365       3221   
1            NaN  02/01/2019     2200         45          365       3161   
2        16600.0  08/12/2016     1000         45          365       2260   
3        17600.0         NaN     2200         45          365       3141   
4        21250.0  28/10/2017     2200         55          365       3570   
...          ...         ...      ...        ...          ...        ...   
1038     17300.0  29/12/2018     2200         45          365       3251   
1039         NaN  28/03/2018     2200         45          365       4090   
1040     17300.0  26/04/2018     2200         45          365       4051   
1041     16300.0  25/10/2016     1000         45          365       1930   
1042     17300.0  15/05/2019     2200         45          365       4451   

      AmtPaid60  AmtPaid360        LoanStatus  
0          4166       14621            Active  
1          4096       16041            Active  
2          3205       16340               NaN  
3          4166       16321            Active  
4          4745       14720            Active  
...         ...         ...               ...  
1038       4743       16617  Finished Payment  
1039       5582       16617  Finished Payment  
1040       5143       16617  Finished Payment  
1041       3462       15617  Finished Payment  
1042       4743       16617  Finished Payment  

[1043 rows x 15 columns]

In [13]:
print(Data)

      LoanID     StringID    Product CustomerGender     Location    Region  \
0          1     LoanID_1  Product B         Female   Location 3  Region 2   
1          2     LoanID_2  Product D         Female   Location 6  Region 6   
2          3     LoanID_3  Product B           Male   Location 8  Region 3   
3          4     LoanID_4  Product A           Male  Location 26  Region 2   
4          5     LoanID_5  Product B         Female  Location 34  Region 3   
...      ...          ...        ...            ...          ...       ...   
1038    1039  LoanID_1039  Product B           Male  Location 73  Region 6   
1039    1040  LoanID_1040  Product A           Male  Location 82  Region 1   
1040    1041  LoanID_1041  Product A   NotSpecified  Location 11  Region 4   
1041    1042  LoanID_1042  Product B         Female  Location 26  Region 6   
1042    1043  LoanID_1043  Product A   NotSpecified  Location 94  Region 6   

      TotalPrice   StartDate  Deposit  DailyRate  TotalDaysYr  

In [14]:
pd.read_csv("Lending-company.csv",index_col="LoanID")

StringID    Product CustomerGender     Location    Region  \
LoanID                                                                 
1          LoanID_1  Product B         Female   Location 3  Region 2   
2          LoanID_2  Product D         Female   Location 6  Region 6   
3          LoanID_3  Product B           Male   Location 8  Region 3   
4          LoanID_4  Product A           Male  Location 26  Region 2   
5          LoanID_5  Product B         Female  Location 34  Region 3   
...             ...        ...            ...          ...       ...   
1039    LoanID_1039  Product B           Male  Location 73  Region 6   
1040    LoanID_1040  Product A           Male  Location 82  Region 1   
1041    LoanID_1041  Product A   NotSpecified  Location 11  Region 4   
1042    LoanID_1042  Product B         Female  Location 26  Region 6   
1043    LoanID_1043  Product A   NotSpecified  Location 94  Region 6   

        TotalPrice   StartDate  Deposit  DailyRate  TotalDaysYr  AmtPaid36  \
LoanID                                                                       
1          17600.0  04/07/2018     2200         45          365       3221   
2              NaN  02/01/2019     2200         45          365       3161   
3          16600.0  08/12/2016     1000         45          365       2260   
4          17600.0         NaN     2200         45          365       3141   
5          21250.0  28/10/2017     2200         55          365       3570   
...            ...         ...      ...        ...          ...        ...   
1039       17300.0  29/12/2018     2200         45          365       3251   
1040           NaN  28/03/2018     2200         45          365       4090   
1041       17300.0  26/04/2018     2200         45          365       4051   
1042       16300.0  25/10/2016     1000         45          365       1930   
1043       17300.0  15/05/2019     2200         45          365       4451   

        AmtPaid60  AmtPaid360        LoanStatus  
LoanID                                           
1            4166       14621            Active  
2            4096       16041            Active  
3            3205       16340               NaN  
4            4166       16321            Active  
5            4745       14720            Active  
...           ...         ...               ...  
1039         4743       16617  Finished Payment  
1040         5582       16617  Finished Payment  
1041         5143       16617  Finished Payment  
1042         3462       15617  Finished Payment  
1043         4743       16617  Finished Payment  

[1043 rows x 14 columns]

In [15]:
df = pd.DataFrame(data=[["Tayyab", 12000, 23]],columns=['Name','Salary','Age'], index=['A','B','C'])
df


Name  Salary  Age
A  Tayyab   12000   23
B  Tayyab   12000   23
C  Tayyab   12000   23

In [16]:
df = pd.DataFrame(data=[['Tayyab',20000,24],['Waleed',20000,24],['Faseeh',20000,24]],columns=['Name','Salary','Age'],index=['A','B','C'])
df

Name  Salary  Age
A  Tayyab   20000   24
B  Waleed   20000   24
C  Faseeh   20000   24

**Importing CSV with pandas**

In [17]:
import numpy as np

**np.loadtxt vs np.genfromtxt**
Load is faster and gen is flexible

In [18]:
lending_numeric_value1= np.loadtxt('Lending-Company-Numeric-Data.csv', delimiter=',')
lending_numeric_value1

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [19]:
lending_numeric_value2= np.genfromtxt('Lending-Company-Numeric-Data-NAN.csv', delimiter=';')
lending_numeric_value2

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [   nan,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

dtype=str

In [20]:
lending_numeric_value2= np.genfromtxt('Lending-Company-Numeric-Data-NAN.csv', delimiter=';',dtype=str)
lending_numeric_value2

array([['2000', '40', '365', '3121', '4241', '13621'],
       ['2000', '40', '365', '3061', '4171', '15041'],
       ['1000', '40', '365', '2160', '3280', '15340'],
       ...,
       ['', '40', '365', '4201', '5001', '16600'],
       ['1000', '40', '365', '2080', '3320', '15600'],
       ['2000', '40', '365', '4601', '4601', '16600']], dtype='<U5')

In [21]:
lending_numeric_value2[0,0]+lending_numeric_value2[0,1]

'200040'

skip_header, skip_footer, usecols(0,1,5), usecols(5,0,1), unpack

In [22]:
lending_numeric_value2= np.genfromtxt('Lending-Company-Numeric-Data-NAN.csv', delimiter=';',skip_header=2)
lending_numeric_value2

array([[ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       [ 2000.,    40.,   365.,  3041.,  4241., 15321.],
       [ 2000.,    50.,   365.,  3470.,  4820., 13720.],
       ...,
       [   nan,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [23]:
lending_numeric_value2= np.genfromtxt('Lending-Company-Numeric-Data-NAN.csv', delimiter=';',skip_footer=2)
lending_numeric_value2

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  3401.,    nan, 16600.],
       [ 2000.,    40.,   365.,    nan,  5440., 16600.],
       [   nan,    40.,   365.,  4201.,  5001., 16600.]])

In [24]:
lending_numeric_value2= np.genfromtxt('Lending-Company-Numeric-Data-NAN.csv', delimiter=';',
                                      skip_header=2,
                                      skip_footer=2,
                                      usecols=(5,1,0))
lending_numeric_value2

array([[15340.,    40.,  1000.],
       [15321.,    40.,  2000.],
       [13720.,    50.,  2000.],
       ...,
       [16600.,    40.,  2000.],
       [16600.,    40.,  2000.],
       [16600.,    40.,    nan]])

In [25]:
#unpack=true
lending_numeric_1,lending_numeric_2,lending_numeric_3,= np.genfromtxt('Lending-Company-Numeric-Data-NAN.csv', delimiter=';',
                                      skip_header=2,
                                      skip_footer=2,
                                      usecols=(5,1,0),
                                      unpack=True)
print(lending_numeric_1)
print(lending_numeric_2)
print(lending_numeric_3)

[15340. 15321. 13720. ... 16600. 16600. 16600.]
[40. 40. 50. ... 40. 40. 40.]
[1000. 2000. 2000. ... 2000. 2000.   nan]


**Import JSON File**

In [26]:
prices_per_product='{"Product":1000,"Product2":2000,"Product3":3000}'
prices_per_product

'{"Product":1000,"Product2":2000,"Product3":3000}'

In [27]:
import json
prices_per_product_json=json.loads(prices_per_product)
type(prices_per_product_json)

dict

In [28]:
lending_company_Json = pd.read_json('Lending-Company.json')
lending_company_Json

Loan ID String_ID    Product CustomerGender      Location    Region  \
0           1      id_1  Product B           Male    Location 2  Region 2   
1           2      id_2  Product B           Male    Location 3  Region 3   
2           3      id_3  Product C         Female    Location 5  Region 5   
3           4      id_4  Product B           Male    Location 6  Region 1   
4           5      id_5  Product D         Female    Location 7  Region 2   
...       ...       ...        ...            ...           ...       ...   
1038     1039   id_1039  Product B         Female   Location 39  Region 6   
1039     1040   id_1040  Product B           Male   Location 50  Region 1   
1040     1041   id_1041  Product B           Male   Location 23  Region 4   
1041     1042   id_1042  Product C   NotSpecified   Location 52  Region 6   
1042     1043   id_1043  Product B         Female  Location 142  Region 6   

      TotalPrice   StartDate  Deposit  DailyRate  TotalDays  AmountPaid30  \
0          16600    7/4/2014     2000         40        365          3121   
1          16600    1/2/2015     2000         40        365          3061   
2          15600   12/8/2012     1000         40        365          2160   
3          16600   2/20/2015     2000         40        365          3041   
4          20250  10/28/2013     2000         50        365          3470   
...          ...         ...      ...        ...        ...           ...   
1038       16600  12/29/2014     2000         40        365          3401   
1039       16600   3/28/2014     2000         40        365          4240   
1040       16600   4/26/2014     2000         40        365          4201   
1041       15600  10/25/2012     1000         40        365          2080   
1042       16600   5/15/2015     2000         40        365          4601   

      AmountPaid60  AmountPaid360     LoanStatus360  
0             4241          13621            Active  
1             4171          15041            Active  
2             3280          15340              None  
3             4241          15321            Active  
4             4820          13720            Active  
...            ...            ...               ...  
1038          4601          16600  Finished Payment  
1039          5440          16600  Finished Payment  
1040          5001          16600  Finished Payment  
1041          3320          15600  Finished Payment  
1042          4601          16600  Finished Payment  

[1043 rows x 15 columns]

In [29]:
type(lending_company_Json)

pandas.core.frame.DataFrame

Working with Excel

In [30]:
excel_data = pd.read_excel('Lending-company.xlsx', index_col='LoanID')
excel_data

StringID    Product CustomerGender      Location    Region  TotalPrice  \
LoanID                                                                          
1          id_1  Product B           Male    Location 2  Region 2     16600.0   
2          id_2  Product B           Male    Location 3  Region 3         NaN   
3          id_3  Product C         Female    Location 5  Region 5     15600.0   
4          id_4  Product B           Male    Location 6  Region 1     16600.0   
5          id_5  Product D         Female    Location 7  Region 2     20250.0   
...         ...        ...            ...           ...       ...         ...   
1039    id_1039  Product B         Female   Location 39  Region 6     16600.0   
1040    id_1040  Product B           Male   Location 50  Region 1         NaN   
1041    id_1041  Product B           Male   Location 23  Region 4     16600.0   
1042    id_1042  Product C   NotSpecified   Location 52  Region 6     15600.0   
1043    id_1043  Product B         Female  Location 142  Region 6     16600.0   

         StartDate  Deposit  DailyRate  TotalDays  AmountPaid30  AmountPaid60  \
LoanID                                                                          
1         7/4/2014     2000         40        365          3121          4241   
2         1/2/2015     2000         40        365          3061          4171   
3        12/8/2012     1000         40        365          2160          3280   
4              NaN     2000         40        365          3041          4241   
5       10/28/2013     2000         50        365          3470          4820   
...            ...      ...        ...        ...           ...           ...   
1039    12/29/2014     2000         40        365          3401          4601   
1040     3/28/2014     2000         40        365          4240          5440   
1041     4/26/2014     2000         40        365          4201          5001   
1042    10/25/2012     1000         40        365          2080          3320   
1043     5/15/2015     2000         40        365          4601          4601   

        AmountPaid360     LoanStatus360  
LoanID                                   
1               13621            Active  
2               15041            Active  
3               15340               NaN  
4               15321            Active  
5               13720            Active  
...               ...               ...  
1039            16600  Finished Payment  
1040            16600  Finished Payment  
1041            16600  Finished Payment  
1042            15600  Finished Payment  
1043            16600  Finished Payment  

[1043 rows x 14 columns]

Working with importing data
sep and delimiter

In [31]:
data = pd.read_csv('Lending-company.csv', usecols=['StringID','Product','TotalPrice','StartDate'], index_col='StringID')
data.head()

Product  TotalPrice   StartDate
StringID                                   
LoanID_1  Product B     17600.0  04/07/2018
LoanID_2  Product D         NaN  02/01/2019
LoanID_3  Product B     16600.0  08/12/2016
LoanID_4  Product A     17600.0         NaN
LoanID_5  Product B     21250.0  28/10/2017

In [32]:
data = pd.read_csv('Lending-company-single-column-data.csv')
data.head()

LoanID,StringID,Product,CustomerGender,Location,Region,TotalPrice,StartDate,Deposit,DailyRate,TotalDaysYr,AmtPaid36,AmtPaid60,AmtPaid360,LoanStatus
0  1,LoanID_1,Product B,Female,Location 3,Region ...                                                                                                 
1  2,LoanID_2,Product D,Female,Location 6,Region ...                                                                                                 
2  3,LoanID_3,Product B,Male,Location 8,Region 3,...                                                                                                 
3  4,LoanID_4,Product A,Male,Location 26,Region 2...                                                                                                 
4  5,LoanID_5,Product B,Female,Location 34,Region...

In [33]:
data = pd.read_csv('Lending-company-single-column-data.csv', sep='\,')
data.head()

C:\Users\Tayyab\AppData\Local\Temp\ipykernel_6932\1694789456.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  data = pd.read_csv('Lending-company-single-column-data.csv', sep='\,')


"LoanID  StringID    Product CustomerGender     Location    Region  \
0      "1  LoanID_1  Product B         Female   Location 3  Region 2   
1      "2  LoanID_2  Product D         Female   Location 6  Region 6   
2      "3  LoanID_3  Product B           Male   Location 8  Region 3   
3      "4  LoanID_4  Product A           Male  Location 26  Region 2   
4      "5  LoanID_5  Product B         Female  Location 34  Region 3   

   TotalPrice   StartDate  Deposit  DailyRate  TotalDaysYr  AmtPaid36  \
0     17600.0  04/07/2018     2200         45          365       3221   
1         NaN  02/01/2019     2200         45          365       3161   
2     16600.0  08/12/2016     1000         45          365       2260   
3     17600.0         NaN     2200         45          365       3141   
4     21250.0  28/10/2017     2200         55          365       3570   

   AmtPaid60  AmtPaid360 LoanStatus"  
0       4166       14621     Active"  
1       4096       16041     Active"  
2       3205       16340           "  
3       4166       16321     Active"  
4       4745       14720     Active"

In [34]:
data = pd.read_csv('Lending-company-single-column-data.csv', sep='\,', engine='python')
data.head()

"LoanID  StringID    Product CustomerGender     Location    Region  \
0      "1  LoanID_1  Product B         Female   Location 3  Region 2   
1      "2  LoanID_2  Product D         Female   Location 6  Region 6   
2      "3  LoanID_3  Product B           Male   Location 8  Region 3   
3      "4  LoanID_4  Product A           Male  Location 26  Region 2   
4      "5  LoanID_5  Product B         Female  Location 34  Region 3   

   TotalPrice   StartDate  Deposit  DailyRate  TotalDaysYr  AmtPaid36  \
0     17600.0  04/07/2018     2200         45          365       3221   
1         NaN  02/01/2019     2200         45          365       3161   
2     16600.0  08/12/2016     1000         45          365       2260   
3     17600.0         NaN     2200         45          365       3141   
4     21250.0  28/10/2017     2200         55          365       3570   

   AmtPaid60  AmtPaid360 LoanStatus"  
0       4166       14621     Active"  
1       4096       16041     Active"  
2       3205       16340           "  
3       4166       16321     Active"  
4       4745       14720     Active"

In [35]:
data = pd.read_csv('Lending-company-single-column-data.csv', delimiter='\,',  engine='python')
data.head()

"LoanID  StringID    Product CustomerGender     Location    Region  \
0      "1  LoanID_1  Product B         Female   Location 3  Region 2   
1      "2  LoanID_2  Product D         Female   Location 6  Region 6   
2      "3  LoanID_3  Product B           Male   Location 8  Region 3   
3      "4  LoanID_4  Product A           Male  Location 26  Region 2   
4      "5  LoanID_5  Product B         Female  Location 34  Region 3   

   TotalPrice   StartDate  Deposit  DailyRate  TotalDaysYr  AmtPaid36  \
0     17600.0  04/07/2018     2200         45          365       3221   
1         NaN  02/01/2019     2200         45          365       3161   
2     16600.0  08/12/2016     1000         45          365       2260   
3     17600.0         NaN     2200         45          365       3141   
4     21250.0  28/10/2017     2200         55          365       3570   

   AmtPaid60  AmtPaid360 LoanStatus"  
0       4166       14621     Active"  
1       4096       16041     Active"  
2       3205       16340           "  
3       4166       16321     Active"  
4       4745       14720     Active"

Squeeze into series

In [36]:
data=pd.read_csv('Customer-Gender.csv')
data=data.head().squeeze()
type(data)

pandas.core.series.Series

In [37]:
data= pd.read_csv('Lending-company.csv',usecols=['Product'])
data=data.head().squeeze()
type(data)



pandas.core.series.Series

 A Note on Importing Files in Jupyter

In [38]:
data=pd.read_csv('C:/ML/The Data Analyst Course Complete Data Analyst Bootcamp 2022/09 - Working with Text Files/Customer-Gender.csv')
data.head()

CustomerGender
0         Female
1         Female
2           Male
3           Male
4         Female

Saving Your Data with pandas

In [39]:
data = pd.read_excel('Lending-company.xlsx', index_col='LoanID')
data.to_csv('Data.csv')
data.to_excel('Data.xlsx')
data.to_json('Data.json')

np.save()  npy

In [40]:
lending_co = np.genfromtxt('Lending-Company-Saving.csv', dtype=str, delimiter=',')
lending_co

array([['LoanID', 'StringID', 'Product', ..., 'Location', 'Region',
        'TotalPrice'],
       ['1', 'id_1', 'Product B', ..., 'Location 2', 'Region 2',
        '16600.0'],
       ['2', 'id_2', 'Product B', ..., 'Location 3', '', '16600.0'],
       ...,
       ['1041', 'id_1041', 'Product B', ..., 'Location 23', 'Region 4',
        '16600.0'],
       ['1042', 'id_1042', 'Product C', ..., 'Location 52', 'Region 6',
        '15600.0'],
       ['1043', 'id_1043', 'Product B', ..., 'Location 142', 'Region 6',
        '16600.0']], dtype='<U14')

In [45]:
np.save('lending_co_saving', lending_co)
lending_co_save = np.load('lending_co_saving.npy')
lending_co_save

array([['LoanID', 'StringID', 'Product', ..., 'Location', 'Region',
        'TotalPrice'],
       ['1', 'id_1', 'Product B', ..., 'Location 2', 'Region 2',
        '16600.0'],
       ['2', 'id_2', 'Product B', ..., 'Location 3', '', '16600.0'],
       ...,
       ['1041', 'id_1041', 'Product B', ..., 'Location 23', 'Region 4',
        '16600.0'],
       ['1042', 'id_1042', 'Product C', ..., 'Location 52', 'Region 6',
        '15600.0'],
       ['1043', 'id_1043', 'Product B', ..., 'Location 142', 'Region 6',
        '16600.0']], dtype='<U14')

np.savez .npz Lending_company_savez.files

In [53]:
np.savez('Lending-company-savez', company = lending_co, data_save = lending_co_save)
Lending_company_savez = np.load('Lending-company-savez.npz')
Lending_company_savez['data_save']
Lending_company_savez.files

['company', 'data_save']

In [59]:
np.savetxt('Lending-Company-Saving.txt', 
           lending_co, 
           delimiter=',',
           fmt='%s')
lending_co_txt = np.genfromtxt('Lending-Company-Saving.txt', 
                               delimiter=',' ,
                               dtype=str)
np.array_equal(lending_co, lending_co_txt)

True